# Generated by Django 3.0.4 on 2020-04-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkSpider',
            fields=[
                ('link_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='序号')),
                ('link_name', models.CharField(max_length=50, verbose_name='链接地址')),
                ('image', models.ImageField(upload_to='../media/index_images', verbose_name='图片')),
                ('title', models.CharField(max_length=55, verbose_name='文章标题')),
            ],
            options={
                'db_table': 'index_link',
            },
        ),
    ]
